### ISSUE TITLE
Issues with background type = "fit"

### ISSUE THREAD

**Issue by krmcmillen** [ergodicio/inverse-thomson-scattering#31]
**Error**
inverse-thomson-scattering/inverse_thomson_scattering/evaluate_background.py", line 174, in get_lineout_bg
    :, BackgroundPixel - config["data"]["dpixel"] : BackgroundPixel + config["data"]["dpixel"]
TypeError: unsupported operand type(s) for -: 'list' and 'int'

**Possible Fix**
"/inverse_thomson_scattering/lineouts.py b/inverse_thomson_scattering/lineouts.py", line 29
From BackgroundPixel = []
To BackgroundPixel = 0

**Error**
"/inverse-thomson-scattering/inverse_thomson_scattering/evaluate_background.py", line 103, in get_lineout_bg
    if config["data"]["background"]["show"]:
KeyError: 'show'

**Possible Fix**
add 
[data][background][show] to inputs.yaml
or
remove lines 103-106

**Comment by almilder** [comment]
This is now fixed on multi-species branch

**Comment by almilder** [comment]
Now merged in
