### ISSUE TITLE
calc_sigmas: True does nothing? 

### ISSUE THREAD

**Issue by zachbarfield60** [ergodicio/inverse-thomson-scattering#49]
sigmas.nc is uploaded on all runs, even when 
```
other:
    calc_sigmas: False
```
The file is filled with a value of "0" for all parameters at all times.
Setting
```
other:
    calc_sigmas: True
```
does not change this.

**Comment by joglekara** [comment]
This is for 1D mode?

**Comment by zachbarfield60** [comment]
> This is for 1D mode?

1D in what sense?

**Comment by joglekara** [comment]
as in not angular

**Comment by zachbarfield60** [comment]
Yes, this is for 1D mode
